// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.
var data = [];
//全局变量
var GV = {
  HOST: "https://hstest.ontheroadstore.com/",
  pay_url :"https://hs.ontheroadstore.com/payment/test_pay/",
  img_url :"https://img8.ontheroadstore.com/"
};
